/**
 * Runs the published negative / adversarial vectors (adversarial-vectors.json)
 * against the reference implementation: every `invalid` vector MUST be rejected
 * (decrypt throws) and every `valid` control MUST decrypt to the known plaintext.
 *
 * This is the enforcement side of the artifact generated by
 * `generate-adversarial.ts`. Any implementation change that stops rejecting a
 * documented attack — or starts rejecting a valid file — fails here. Requires
 * `dist/` (run `npm run build` first, like the other vector tests).
 */

import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

import { hexToBytes } from '../../src/internal/encoding.js'
import { SUITE } from '../../src/internal/types.js'
import * as aesV1 from '../../src/suites/aes-gcm-v1/api.js'
import * as aesV2 from '../../src/suites/aes-gcm-v2/api.js'
import * as xchacha from '../../src/suites/xchacha-v1/api.js'
import * as pqHybrid from '../../src/suites/pq-hybrid-v1/api.js'
import { deriveMlKemKeypair } from '../../src/suites/pq-hybrid-v1/index.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

function fixedBytes(byte: number, length: number): Uint8Array {
  const out = new Uint8Array(length)
  out.fill(byte)
  return out
}

// Same fixed key material the generator used.
const CONTENT_KEY = fixedBytes(0x11, 32)
const ENVELOPE_KEY = fixedBytes(0x22, 32)
let pqKeys: { publicKey: Uint8Array; secretKey: Uint8Array } | null = null
async function pqSecret(): Promise<Uint8Array> {
  if (!pqKeys) pqKeys = await deriveMlKemKeypair(fixedBytes(0x00, 32))
  return pqKeys.secretKey
}

async function decryptFor(suiteId: string, bytes: Uint8Array): Promise<Uint8Array> {
  const blob = new Blob([bytes as Uint8Array<ArrayBuffer>])
  switch (suiteId) {
    case 'aes-gcm-v1':
      return new Uint8Array(await (await aesV1.decryptBlob({ blob, contentKey: CONTENT_KEY })).arrayBuffer())
    case 'aes-gcm-v2':
      return new Uint8Array(await (await aesV2.decryptBlob({ blob, contentKey: CONTENT_KEY })).arrayBuffer())
    case 'xchacha-v1':
      return new Uint8Array(await (await xchacha.decryptBlob({ blob, contentKey: CONTENT_KEY })).arrayBuffer())
    case 'pq-hybrid-v1':
      return new Uint8Array(
        await (
          await pqHybrid.decryptBlob({
            blob,
            recipientSecretKey: await pqSecret(),
            envelopeKey: ENVELOPE_KEY,
          })
        ).arrayBuffer(),
      )
    default:
      throw new Error(`unknown suite id in vectors: ${suiteId}`)
  }
}

interface Vector {
  id: string
  attackClass: string
  result: 'valid' | 'invalid'
  comment: string
  file_hex: string
}
interface VectorFile {
  plaintext_hex: string
  groups: Record<string, Vector[]>
}

const data: VectorFile = JSON.parse(
  readFileSync(resolve(__dirname, 'adversarial-vectors.json'), 'utf8'),
)
const EXPECTED_PLAINTEXT = hexToBytes(data.plaintext_hex)

// Sanity: the suite ids in the file are the ones we know how to drive, and
// every suite carries both invalid vectors and a valid control.
for (const [suiteId, vectors] of Object.entries(data.groups)) {
  test(`adversarial: ${suiteId} — suite is recognized and has coverage`, () => {
    assert.ok(
      [SUITE.AES_256_GCM_V1, SUITE.AES_256_GCM_V2, SUITE.XCHACHA20_POLY1305_V1, SUITE.PQ_HYBRID_XCHACHA_MLKEM1024_V1]
        .length > 0,
    )
    assert.ok(vectors.some((v) => v.result === 'invalid'), `${suiteId}: no invalid vectors`)
    assert.ok(vectors.some((v) => v.result === 'valid'), `${suiteId}: no valid control`)
  })

  for (const v of vectors) {
    if (v.result === 'invalid') {
      test(`adversarial: ${v.id} — MUST reject (${v.attackClass})`, async () => {
        await assert.rejects(
          () => decryptFor(suiteId, hexToBytes(v.file_hex)),
          `expected rejection but decrypt succeeded: ${v.comment}`,
        )
      })
    } else {
      test(`adversarial: ${v.id} — MUST accept and recover plaintext`, async () => {
        const pt = await decryptFor(suiteId, hexToBytes(v.file_hex))
        assert.deepEqual(pt, EXPECTED_PLAINTEXT)
      })
    }
  }
}
